---

version: '2.3'

services:
  nameserver:
    image: unbound:latest
    build: ..
    environment:
      ENABLE_CATCH_ALL: 'true'
      UPSTREAM_PRIMARY: 9.9.9.9
      LAZY_CONTROL_SETUP: 'true'
    networks:
      - resolver
    volumes_from:
      # normally you would provide the catch-all forwarder
      # zone as well with this config volume.
      - config
  config:
    image: alpine:3.7
    volumes:
      - ./config:/etc/unbound/conf.d
  consumer:
    image: unbound-example-consumer:latest
    build: ./consumer
    command: [ "dig", "@nameserver", "local.example.com", "+short" ]
    networks:
      - resolver
    depends_on:
      - nameserver

networks:
  resolver: